version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  spark-master:
    image: apache/spark:3.5.6
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark Master

  spark-worker:
    image: apache/spark:3.5.6
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master

  python:
    build: .
    container_name: python-dev
    volumes:
      - .:/app
    depends_on:
      - cassandra
      - spark-master
    tty: true
    stdin_open: true

volumes:
  cassandra_data:
